== FusionAuth::FusionAuthClient

This gem is the Ruby client library that helps connect Ruby applications to the FusionAuth (https://fusionauth.io) Identity and User Management platform.

=== Installation

Add this line to your application’s Gemfile:

[source,ruby]
----
gem 'fusionauth_client'
----

And then execute:

....
$ bundle
....

Or install it yourself as:

....
$ gem install fusionauth_client
....

=== Usage

Once the gem is installed, you can call FusionAuth APIs.

See examples in the `examples` directory.

=== Questions and support

If you have a question or support issue regarding this client library, we’d love to hear from you.

If you have a paid edition with support included, please https://account.fusionauth.io/account/support/[open a ticket in your account portal]. Learn more about https://fusionauth.io/pricing[paid editions here].

Otherwise, please https://fusionauth.io/community/forum/[post your question in the community forum].

=== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/FusionAuth/fusionauth-ruby-client.

=== License

This code is available as open source under the terms of the https://opensource.org/licenses/Apache-2.0[Apache v2.0 License].
