name: Generate Docs

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Generate docs
      run: |
        rm -f doc/index.db
        rdoc --format=markdown lib/fusionauth/fusionauth_client.rb

    - name: Commit
      uses: EndBug/add-and-commit@v9 
      with:
        add: 'doc/'
        message: ':memo: Updating docs'

